### ISSUE TITLE
Fastify cors > v2.1.3 causes fastify schema compiler build error

### ISSUE THREAD

**Issue by weiliddat** [fastify/fastify-cors#47]
## 💥 Regression Report

Upgrading from fastify-cors@2.1.3 to fastify-cors@2.2.0 and beyond causes some shared schema failures.

## Last working version

Worked up to version: 2.1.3

Stopped working in version: 2.2.0, 3.0.0

## To Reproduce

1. Install fastify, fastify-cors, fastify-plugin
2. Run the following code `node index.js`

```js
const fastify = require('fastify')({ logger: true });
const cors = require('fastify-cors');
const fp = require('fastify-plugin');

const sharedSchemas = fp(
    async f => {
        f.addSchema({
            $id: 'https://example.com/bson',
            type: 'object',
            types: {
                objectId: {
                    type: 'string',
                    pattern: '\\b[0-9A-Fa-f]{24}\\b',
                },
            }
        });
    }
);

async function main() {
    await fastify.register(cors);
    await fastify.register(sharedSchemas);

    console.dir(fastify.getSchemas());

    fastify.route({
        method: 'GET',
        url: '/:id',
        schema: {
            params: {
                type: 'object',
                properties: {
                    id: { $ref: 'https://example.com/bson#/types/objectId' },
                },
            },
        },
        handler: async (req) => ({ hello: req.params.id }),
    });

    await fastify.listen('1337', '127.0.0.1');
}

main().catch(console.error);

```

This spits out the error
```
FastifyError [FST_ERR_SCH_BUILD]: FST_ERR_SCH_BUILD: Failed building the schema for GET: /:id, due error can't resolve reference https://example.com/bson#/types/objectId from id #
    at Object.afterRouteAdded (/contrib/fastify-cors-schema/node_modules/fastify/lib/route.js:232:37)
    at /contrib/fastify-cors-schema/node_modules/fastify/lib/route.js:168:25
    at Object._encapsulateThreeParam (/contrib/fastify-cors-schema/node_modules/avvio/boot.js:417:7)
    at Boot.callWithCbOrNextTick (/contrib/fastify-cors-schema/node_modules/avvio/boot.js:339:5)
    at Boot._after (/contrib/fastify-cors-schema/node_modules/avvio/boot.js:230:26)
    at Plugin.exec (/contrib/fastify-cors-schema/node_modules/avvio/plugin.js:89:17)
    at Boot.loadPlugin (/contrib/fastify-cors-schema/node_modules/avvio/plugin.js:175:10)
    at Task.release (/contrib/fastify-cors-schema/node_modules/fastq/queue.js:127:16)
    at worked (/contrib/fastify-cors-schema/node_modules/fastq/queue.js:169:10)
    at /contrib/fastify-cors-schema/node_modules/avvio/plugin.js:178:7 {
  name: 'FastifyError [FST_ERR_SCH_BUILD]',
  code: 'FST_ERR_SCH_BUILD',
  message: "FST_ERR_SCH_BUILD: Failed building the schema for GET: /:id, due error can't resolve reference https://example.com/bson#/types/objectId from id #",
  statusCode: 500
}
```

## Expected behavior

Schemas shouldn't be affected by a cors plugin.
If you run `npm install fastify-cors@2.1.3`, then run `node index.js` again, everything is fine.

## Your Environment

- *node version*: 12
- *fastify version*: >=2.0.0
- *os*: Mac
- *any other relevant information*

**Comment by weiliddat** [comment]
The line that adds some default options for the OPTIONS response seem to be affecting it - perhaps because it sets a default schema that isn't merged?
I'm just guessing because commenting out line 36 (snippet below) in fastify-cors' index.js seems to avoid this issue, and was introduced in 2.2.0.
```js
  if (preflight === true) {
    fastify.options('*', { schema: { hide: hideOptionsRoute } }, (req, reply) => reply.send())
  }
```

**Comment by Eomm** [comment]
We should investigate, but if you switch 

```
    await fastify.register(sharedSchemas);
    await fastify.register(cors);
```

it seems to work

**Comment by weiliddat** [comment]
Hmm OK, after some debugging I'm not sure if it's just my misunderstanding on the conceptual/documentation thing on fastify's schema, route, and plugin encapsulation.
Maybe it makes sense to move this to the `fastify` repo instead because it's not really a cors plugin issue.

@Eomm you seem to be also doing some work on the schema compilation/registration so I guess you're the best person to ask about this.

Some things I found out:
1. Registering a route with a schema option before registering the schema in a plugin, then using the schema. This causes the schema compiler to run twice, but on the second run it doesn't have the same list of schemas to compile, causing it to throw a reference error.

```js
const fastify = require('fastify')({ logger: true });
const fp = require('fastify-plugin');

fastify.get('/', { schema: {} }, (req, reply) => reply.send());

fastify.register(fp(async f => f.addSchema({
    $id: 'https://example.com/bson/objectId',
    type: 'string',
    pattern: '\\b[0-9A-Fa-f]{24}\\b',
})));

fastify.get('/:id', {
    schema: {
        params: {
            type: 'object',
            properties: {
                id: { $ref: 'https://example.com/bson/objectId#' },
            },
        },
    },
    handler: async (req) => ({ hello: req.params.id }),
});

fastify.listen('1337', '127.0.0.1');
```

2. Moving the schema registration out of the plugin makes it fine then. I'm not sure why? I thought running the plugin through `fastify-plugin` should also avail the schemas to whatever is in the registration scope, but it seems I'm wrong about this.

The server below runs fine, and schemas compile and throw the correct error if the routes do not fulfill the pattern.

```js
const fastify = require('fastify')({ logger: true });

fastify.get('/', { schema: {} }, (req, reply) => reply.send());

fastify.addSchema({
    $id: 'https://example.com/bson/objectId',
    type: 'string',
    pattern: '\\b[0-9A-Fa-f]{24}\\b',
});

fastify.get('/:id', {
    schema: {
        params: {
            type: 'object',
            properties: {
                id: { $ref: 'https://example.com/bson/objectId#' },
            },
        },
    },
    handler: async (req) => ({ hello: req.params.id }),
});

fastify.listen('1337', '127.0.0.1');
```

3. Not having any routes that do not use schema options before the schema is registered in a plugin also makes it work.

```js
const fastify = require('fastify')({ logger: true });
const fp = require('fastify-plugin');

fastify.get('/', (req, reply) => reply.send());

fastify.register(fp(async f => f.addSchema({
    $id: 'https://example.com/bson/objectId',
    type: 'string',
    pattern: '\\b[0-9A-Fa-f]{24}\\b',
})));

fastify.get('/:id', {
    schema: {
        params: {
            type: 'object',
            properties: {
                id: { $ref: 'https://example.com/bson/objectId#' },
            },
        },
    },
    handler: async (req) => ({ hello: req.params.id }),
});

fastify.listen('1337', '127.0.0.1');
```

**Comment by weiliddat** [comment]
I'm closing this and opening an issue in `fastify` instead.

**Comment by Eomm** [comment]
> but it seems I'm wrong about this.

No, you are right.

> This causes the schema compiler to run twice

I think this is the error, my thought is that the schemas are consumed and the `$id` is removed.

We will check in  the other issue 👍
