### ISSUE TITLE
CORS is breaking Schemas

### ISSUE THREAD

**Issue by wandersonwhcr** [fastify/fastify-cors#79]
#  🐛 Bug Report

If I define a schema inside a plugin, `fastify-cors` breaks the application when `preflight` is enabled.

## To Reproduce

I created a simple repository showing the problem.

https://github.com/wandersonwhcr/fastify-cors-problem

## Your Environment

- *node version*: 14
- *fastify version*: >=3.1.1
- *os*: Linux

**Comment by wandersonwhcr** [comment]
A workaround to this problem is to register the `fastify-cors` plugin after all plugins.

**Comment by wandersonwhcr** [comment]
I don't know, but now I am thinking this problem can be avoided using `fastify-plugin`.

**Comment by mcollina** [comment]
how is it breaking?

**Comment by wandersonwhcr** [comment]
If you run my source code, you will see.

**Comment by Eomm** [comment]
> If you run my source code, you will see.

I run your code and I didn't see anything.

![image](https://user-images.githubusercontent.com/11404065/89223160-9b184c80-d5d6-11ea-8094-320596c34e31.png)

Please, be more collaborative.

**Comment by wandersonwhcr** [comment]
More collaborative?

TY.

```plain
wanderson@localhost:~/Downloads/fastify-cors-problem$ docker run --rm --interactive --tty \
>   --user `id -u`:`id -g` \
>   --volume `pwd`:/app \
>   --workdir /app \
>   --env PORT=3000 \
>   --env FASTIFY_CORS_PREFLIGHT=1 \
>   --publish 3000:3000 \
>   node npm start

> @wandersonwhcr/fastify-cors-problem@1.0.0-alpha start /app
> node server.js

{"level":50,"time":1596538347118,"pid":18,"hostname":"9ca2e0dd8302","name":"FastifyError","code":"FST_ERR_SCH_VALIDATION_BUILD","message":"Failed building the validation schema for GET: /v1/foobar/:foobarId, due to error can't resolve reference identifier# from id #","statusCode":500,"stack":"FastifyError: Failed building the validation schema for GET: /v1/foobar/:foobarId, due to error can't resolve reference identifier# from id #\n    at Boot.<anonymous> (/app/node_modules/fastify/lib/route.js:261:19)\n    at Object.onceWrapper (events.js:420:28)\n    at Boot.emit (events.js:326:22)\n    at /app/node_modules/avvio/boot.js:153:12\n    at /app/node_modules/avvio/plugin.js:269:7\n    at done (/app/node_modules/avvio/plugin.js:201:5)\n    at check (/app/node_modules/avvio/plugin.js:225:9)\n    at internal/process/task_queues.js:149:7\n    at AsyncResource.runInAsyncScope (async_hooks.js:189:9)\n    at AsyncResource.runMicrotask (internal/process/task_queues.js:146:8)","type":"Error","msg":"Failed building the validation schema for GET: /v1/foobar/:foobarId, due to error can't resolve reference identifier# from id #"}
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! @wandersonwhcr/fastify-cors-problem@1.0.0-alpha start: `node server.js`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the @wandersonwhcr/fastify-cors-problem@1.0.0-alpha start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-08-04T10_52_27_126Z-debug.log
```

**Comment by fox1t** [comment]
I've just reproduced your error (without using docker to run it). I think this is worth more investigation.

**Comment by fox1t** [comment]
OK after some testing I found the issue: there is a problem on https://github.com/fastify/fastify/blob/v3.1.1/lib/route.js#L259
that is called with sBucket as 3rd parameter but going to https://github.com/fastify/fastify/blob/f4cb706144bbf2ebb67257914f78020126488ba5/lib/validation.js#L28 I don't see any use of it. Is this the wanted behavior?
sBucket is
```json
{"store":{"identifier":{"$id":"identifier","type":"string","format":"uuid"}}}
```
@wandersonwhcr moving fastify-cors to be the last plugin executes the 
```
fastify.addSchema({
    $id: 'identifier',
    type: 'string',
    format: 'uuid',
  });
```
before calling fastify-cors and the schema ref is correctely added to "global" schema definition before registering fastify-cors. You can move `.addSchema` to top level to obtain the same (working) result. In `server.js`
```js
const fastify = require('fastify')({ logger: true });


fastify.addSchema({
  $id: 'identifier',
  type: 'string',
  format: 'uuid',
});

fastify.register(require('fastify-cors'), { preflight: process.env.FASTIFY_CORS_PREFLIGHT === '1' });

fastify.register(require('./foobar-plugin.js'), { prefix: '/v1/foobar' });

fastify.listen(process.env.PORT, '0.0.0.0')
  .catch((error) => { fastify.log.error(error); process.exit(255); });
```

**Comment by Eomm** [comment]
> More collaborative?

Long story short: run a project takes time and maybe we are on vacation even.
With a stack trace, we can focus on the issue since we could see it already and we could suggest a solution.

> Is this the wanted behavior?

It should be a misprint due the refactoring. sBucket (aka schemaBucket) is needed only here:

https://github.com/fastify/fastify/blob/f4cb706144bbf2ebb67257914f78020126488ba5/lib/route.js#L256

The line you pointed out can be cleaned.

> OK after some testing I found the issue

Did you recreate it? I run `npm ci` but the server starts in any case.

The issue due the order of execution of `addSchema` is older than the version used in the example package.json:

https://github.com/wandersonwhcr/fastify-cors-problem/blob/68b2ece93b07a5a44ec3fc4792c7497a7c1cf2d8/package.json#L17-L18

**Comment by fox1t** [comment]
@Eomm both `npm i` and `npm ci` makes my server crash because of `.addSchema` ordering.

**Comment by fox1t** [comment]
When this crash occurs, in `node_modules/ajv/lib/dotjs/ref.js` the line `var $refVal = it.resolveRef(it.baseId, $schema, it.isRoot);` assigns `undefined` because  
```json
     "identifier": {
        "id": "identifier",
        "schema": {
          "$id": "identifier",
          "type": "string",
          "format": "uuid"
        },
        "localRefs": {},
        "cacheKey": "{\"$id\":\"identifier\",\"format\":\"uuid\",\"type\":\"string\"}"
      }
```
is missing from `it`.

**Comment by fox1t** [comment]
I've found the real issue. When `preflight: true` this function https://github.com/fastify/fastify/blob/283a1bde631645dc65b6499a29b16ccb95c89823/lib/schema-compilers.js#L12 is called with `externalSchemas === undefined`,  on the other hand if `preflight: true` `externalSchemas` is: 
```js
{"identifier":{"$id":"identifier","type":"string","format":"uuid"}}
```

**Comment by jsumners** [comment]
I bet it's tied to https://github.com/fastify/fastify/issues/2446

**Comment by Eomm** [comment]
Just recreated the minimal test, working on it.

```
test('Schema bucket update itself', t => {
  t.plan(1)
  const fastify = Fastify()

  fastify.options('/', { schema: { hide: true } }, echoBody)

  fastify.register(function (fastify, options, done) {
    fastify.addSchema({
      $id: 'identifier',
      type: 'string',
      format: 'uuid'
    })

    fastify.get('/:foobarId', {
      schema: {
        params: {
          foobarId: { $ref: 'identifier#' }
        }
      }
    }, echoBody)

    done()
  })

  fastify.ready(err => { t.error(err) })
})
```

Moving to fastify repo
